# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20170626_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tripfriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='firstapp.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripfriend',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Trip'),
        ),
    ]
