# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 17:16
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20170626_1314'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tripfriend',
            managers=[
                ('tripfriendsManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
